'use strict';
/* global setInterval, location */
let data = window.KUNKUN_DATA;
const $ = (id) => document.getElementById(id);
function el(tag, text, cls) { const n = document.createElement(tag); if(text !== undefined)n.textContent=text;if(cls)n.className=cls;return n; }
const number = (n) => n === null || n === undefined || n === '' ? '未录入' : Number(n).toLocaleString('zh-CN',{maximumFractionDigits:2});
function findPlayers(players,query){return window.KunkunTables.findPlayers(players,query);}
window.KunkunQuery={findPlayers};
if(!data){$('results').replaceChildren(el('p','数据加载失败，请刷新页面。','warning'));throw Error('Missing public data');}
$('updated').textContent='更新于 '+data.updatedAt.replace('T',' ').slice(0,16);
$('notice').textContent=data.notice;
for(const [count,label] of [[data.players.length,'玩家记录'],[data.characters.length,'人物资料'],[data.characters.filter(c=>c.owner).length,'已有冠名的人物']]){const n=el('div');n.append(el('strong',number(count)),el('span',label));$('overview').append(n);}
$('search-form').addEventListener('submit',e=>{e.preventDefault();const q=$('nickname').value.trim();const out=$('results');out.replaceChildren();if(!q){out.append(el('p','请先输入玩家昵称。','empty'));return;}const matches=findPlayers(data.players,q);if(!matches.length){out.append(el('p','没有找到这个昵称。请检查空格、符号，或私信坤坤确认记录。','empty'));return;}if(matches.length>1)out.append(el('p','找到多个匹配昵称，请选择并核对你的记录。','warning'));for(const p of matches){const card=el('article',undefined,'result');const head=el('div',undefined,'result-head');head.append(el('h3',p.nickname),el('span',p.label||'玩家记录','badge'));card.append(head);const grid=el('div',undefined,'balance-grid');for(const [label,value] of [['冠名碎片',p.fragments],['报名票',p.tickets],['冠名人物数',p.namings===null?null:p.namings.length]]){const cell=el('div',undefined,'balance');cell.append(el('span',label),el('strong',number(value)));grid.append(cell);}card.append(grid,el('p','冠名人物','muted'));const names=el('div',undefined,'chips');if(p.namings===null)names.append(el('span','冠名归属尚待核对','muted'));else if(!p.namings.length)names.append(el('span','当前没有已记录的冠名人物','muted'));else for(const name of p.namings)names.append(el('span',name,'chip'));card.append(names);if(p.note)card.append(el('p',p.note,'notice'));out.append(card);}});
const sortRecords=window.KunkunTables.sortRecords;
let page=1;const pageSize=20;let excludeOwned=false;let filtered=sortRecords(window.KunkunTables.excludeBloodCharacters(data.characters,data.bloodbags||[]),'cost');
function renderCharacters(){const total=Math.max(1,Math.ceil(filtered.length/pageSize));page=Math.min(page,total);const body=$('character-rows');body.replaceChildren();for(const c of filtered.slice((page-1)*pageSize,page*pageSize)){const row=el('tr');row.append(el('td',c.name),el('td',c.owner||'暂无冠名'),el('td',c.cost===null?'待确认':number(c.cost)));body.append(row);}if(!filtered.length){const row=el('tr');const cell=el('td','没有符合条件的人物');cell.colSpan=3;row.append(cell);body.append(row);}$('character-count').textContent='共 '+filtered.length+' 个人物';$('page').textContent=page+' / '+total;$('prev').disabled=page===1;$('next').disabled=page===total;}
function filterCharacters(){const q=$('character-search').value.trim().toLocaleLowerCase();filtered=sortRecords(window.KunkunTables.excludeBloodCharacters(data.characters,data.bloodbags||[]).filter(c=>(c.name+' '+c.owner).toLocaleLowerCase().includes(q)&&(!excludeOwned||!c.owner)),'cost');page=1;renderCharacters();}
$('character-search').addEventListener('input',filterCharacters);$('exclude-owned').addEventListener('click',()=>{excludeOwned=!excludeOwned;$('exclude-owned').setAttribute('aria-pressed',String(excludeOwned));$('exclude-owned').textContent=excludeOwned?'已排除冠名 · 点击恢复':'排除已有冠名';filterCharacters();});$('prev').addEventListener('click',()=>{page--;renderCharacters();});$('next').addEventListener('click',()=>{page++;renderCharacters();});renderCharacters();
const views=['catalog','ranking','blood','custom'];
function setView(view){for(const id of views){const selected=id===view;$(id+'-tab').setAttribute('aria-selected',String(selected));$(id+'-tab').tabIndex=selected?0:-1;$(id+'-panel').hidden=!selected;}}
for(const id of views){$(id+'-tab').addEventListener('click',()=>setView(id));$(id+'-tab').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const index=views.indexOf(id);const target=e.key==='Home'?views[0]:e.key==='End'?views[3]:views[(index+(e.key==='ArrowLeft'?3:1))%4];setView(target);$(target+'-tab').focus();}});}setView('catalog');
let rankPage=1;let hideZero=false;
function renderRank(){const sorted=sortRecords(window.KunkunTables.mergePlayers(data.players).filter(p=>!hideZero||p.fragments===null||Number(p.fragments)!==0),'fragments',$('rank-order').value).map((p,i)=>({player:p,position:i+1}));const q=$('rank-search').value.trim().toLocaleLowerCase();const rows=sorted.filter(({player:p})=>(p.nickname+' '+p.label).toLocaleLowerCase().includes(q));const pages=Math.max(1,Math.ceil(rows.length/pageSize));rankPage=Math.min(rankPage,pages);$('rank-rows').replaceChildren();for(const {player:p,position} of rows.slice((rankPage-1)*pageSize,rankPage*pageSize)){const row=el('tr');row.append(el('td',p.fragments===null?'—':String(position)),el('td',p.nickname),el('td',p.label||'—'),el('td',number(p.fragments)));$('rank-rows').append(row);}if(!rows.length){const row=el('tr');const cell=el('td','没有符合条件的玩家');cell.colSpan=4;row.append(cell);$('rank-rows').append(row);}$('rank-count').textContent='共 '+rows.length+' 条玩家记录';$('rank-page').textContent=rankPage+' / '+pages;$('rank-prev').disabled=rankPage===1;$('rank-next').disabled=rankPage===pages;}
$('hide-zero').addEventListener('click',()=>{hideZero=!hideZero;rankPage=1;$('hide-zero').setAttribute('aria-pressed',String(hideZero));$('hide-zero').textContent=hideZero?'已屏蔽零碎片 · 点击恢复':'屏蔽零碎片玩家';renderRank();});
for(const [id,event] of [['rank-search','input'],['rank-order','change']])$(id).addEventListener(event,()=>{rankPage=1;renderRank();});$('rank-prev').addEventListener('click',()=>{rankPage--;renderRank();});$('rank-next').addEventListener('click',()=>{rankPage++;renderRank();});renderRank();
let bloodPage=1;let excludeOwnedBlood=false;let bloodbags=data.bloodbags||[];
function readableRules(value){return value.replace(/[ \t]+/g,' ').replace(/ +(?=\d\.)/g,'\n').trim();}
$('blood-rules').textContent=readableRules(data.bloodRules||'玩法说明尚未录入，请私信坤坤确认。');$('naming-rules').textContent=readableRules(data.namingRules||'规则尚未录入，请私信坤坤确认。');
function renderBlood(){const q=$('blood-search').value.trim().toLocaleLowerCase();const rows=sortRecords(bloodbags.map(b=>({...b,level:window.KunkunTables.bloodLevel(b)})).filter(b=>(b.name+' '+b.owner).toLocaleLowerCase().includes(q)&&(!excludeOwnedBlood||!b.owner.trim())),'level',$('blood-order').value);const pages=Math.max(1,Math.ceil(rows.length/pageSize));bloodPage=Math.min(bloodPage,pages);$('blood-rows').replaceChildren();for(const b of rows.slice((bloodPage-1)*pageSize,bloodPage*pageSize)){const row=el('tr');row.append(el('td',b.name),el('td',b.owner||'未录入'),...['level','attack','defense','health'].map(field=>el('td',number(b[field]??0))));$('blood-rows').append(row);}if(!rows.length){const row=el('tr');const cell=el('td','没有符合条件的血包人物');cell.colSpan=6;row.append(cell);$('blood-rows').append(row);}$('blood-count').textContent='共 '+rows.length+' 个血包人物';$('blood-page').textContent=bloodPage+' / '+pages;$('blood-prev').disabled=bloodPage===1;$('blood-next').disabled=bloodPage===pages;}
$('blood-order').addEventListener('change',()=>{bloodPage=1;renderBlood();});$('blood-exclude-owned').addEventListener('click',()=>{excludeOwnedBlood=!excludeOwnedBlood;$('blood-exclude-owned').setAttribute('aria-pressed',String(excludeOwnedBlood));$('blood-exclude-owned').textContent=excludeOwnedBlood?'恢复全部血包':'屏蔽已有冠名血包';bloodPage=1;renderBlood();});$('blood-search').addEventListener('input',()=>{bloodPage=1;renderBlood();});$('blood-prev').addEventListener('click',()=>{bloodPage--;renderBlood();});$('blood-next').addEventListener('click',()=>{bloodPage++;renderBlood();});renderBlood();
let refreshing=false;
async function checkUpdates(){if(refreshing||document.hidden||location.protocol==='file:')return;refreshing=true;try{const response=await fetch('data.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)return;const next=await response.json();if(next.updatedAt===data.updatedAt||!Array.isArray(next.players)||!Array.isArray(next.characters))return;data=next;bloodbags=data.bloodbags||[];$('updated').textContent='更新于 '+data.updatedAt.replace('T',' ').slice(0,16);$('notice').textContent=data.notice;$('blood-rules').textContent=readableRules(data.bloodRules||'玩法说明尚未录入');$('naming-rules').textContent=readableRules(data.namingRules||'规则尚未录入');$('overview').replaceChildren();for(const [count,label]of [[data.players.length,'玩家记录'],[data.characters.length,'人物资料'],[data.characters.filter(c=>c.owner).length,'已有冠名的人物']]){const n=el('div');n.append(el('strong',number(count)),el('span',label));$('overview').append(n);}filterCharacters();renderRank();renderBlood();if($('nickname').value.trim())$('search-form').requestSubmit();}catch{/* Offline pages keep showing the last successfully loaded records. */}finally{refreshing=false;}}
setInterval(checkUpdates,30000);window.addEventListener('focus',checkUpdates);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkUpdates();});
